#!/bin/bash
cat results
pypy3 test_blackjack.py --count 1000 --model always_stand --pen 6 
pypy3 test_blackjack.py --count 1000 --model always_hit --pen 6 
pypy3 test_blackjack.py --count 1000 --model hit_until --pen 6 
pypy3 test_blackjack.py --count 1000 --model gambler --pen 6 
pypy3 test_blackjack.py --count 1000 --model basic --pen 6 
echo "MCTS example"
pypy3 test_blackjack.py --count 1 --model mcts --pen 6 --time 0.1
echo "MCTS without counting cards"
pypy3 test_blackjack.py --count 1 --model mcts_no_tracking --pen 6 --time 0.1
echo "Q-Learning with 1 second, 10 seconds, and 20 seconds"
pypy3 test_blackjack.py --count 1000 --model qlearn --pen 6 --time 20
